// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIdleTime() {
  return window['go']['main']['App']['GetIdleTime']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PS() {
  return window['go']['main']['App']['PS']();
}

export function Test() {
  return window['go']['main']['App']['Test']();
}
